config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "pollution_events#index"

  resources :pollution_events do
    resources :comments, only: [:new, :create, :update, :edit, :destroy]
  end

  namespace :api do
    resources :pollution_events, only: [:index]
  end
end

app/models/pollution_event.rb
class PollutionEvent < ActiveRecord::Base
  belongs_to :user
  has_many :comments

  validates :title, presence: true
  validates :address, presence: true
  validates :description, presence: true
  validates :url, presence: true
  validates :event_lng, presence: true, numericality: { greater_than_or_equal_to: -180, less_than_or_equal_to: 180 }
  validates :event_lat, presence: true, numericality: { greater_than_or_equal_to: -90, less_than_or_equal_to: 90 }
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :pollution_events
  has_many :comments
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :email, uniqueness: true
  validates :username, presence: true, uniqueness: true
  validates :encrypted_password, presence: true
end

app/controllers/api/pollution_events_controller.rb
class Api::PollutionEventsController < ApiController
  def index
    events = PollutionEvent.all
    render json: { events: events }, status: :ok
  end
end

app/controllers/api_controller.rb
class ApiController < ApplicationController
  protect_from_forgery with: :null_session
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  helper_method :resource_name, :resource, :devise_mapping

 def resource_name
   :user
 end

 def resource
   @resource ||= User.new
 end

 def devise_mapping
   @devise_mapping ||= Devise.mappings[:user]
 end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :email])
  end
end

app/controllers/pollution_events_controller.rb
class PollutionEventsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  helper_method :resource

  def index
    @pollution_events = PollutionEvent.order(id: :desc)
    @pollution_event = PollutionEvent.new
  end

  def new
    @pollution_event = PollutionEvent.new
  end

  def create
    @pollution_event = PollutionEvent.new(pollution_params)
    @pollution_event.user = current_user
    if @pollution_event.save
      flash[:notice] = "Event created successfully"
      redirect_to root_path
    else
      flash.now[:error] = @pollution_event.errors.full_messages.join(", ")
      render :new
    end
  end

  def show
    @pollution_event = PollutionEvent.find(params[:id])
  end

  def edit
    @pollution_event = PollutionEvent.find(params[:id])
  end

  def update
    @pollution_event = PollutionEvent.find(params[:id])
    if @pollution_event.update_attributes(pollution_params)
      flash[:notice] = "Event updated!"
      redirect_to pollution_event_path(@pollution_event)
    else
      flash.now[:error] = @pollution_event.errors.full_messages.join(", ")
      render :edit
    end
  end

  def destroy
    @pollution_event = PollutionEvent.find(params[:id])
    @pollution_event.destroy
    flash[:notice] = "Event deleted!"
    redirect_to pollution_events_path
  end

  def pollution_params
    params.require(:pollution_event).permit(:title, :address, :description, :url, :likecount, :event_lng, :event_lat)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/_form.erb
<%= form_for [@pollution_event, @comment] do |f|%>
  <div class="row">
    <div class="small-12 medium-6 columns">
      <%= f.label :body, "Comment" %>
      <%= f.text_area :body %>
    </div>
  </div>
  <div class="row">
    <div class="small-12 columns">
      <%= f.submit "Submit Comment", class: "button" %>
    </div>
  </div>
<% end %>

app/views/comments/new.html.erb
<div class="row">
  <div class="small-12 medium-6 columns text-center">
    <h1 class="form-header">Comment Form</h1>
  </div>
</div>
<%= render "comments/form" %>

app/views/layouts/_top_bar.erb
<div class="top-bar">
  <div class="top-bar-left">
    <h2 class="site-logo"style="color:white;"><%= link_to "Pollute This Page", root_path %></h2>
  </div>
  <div class="top-bar-right">
    <ul class="dropdown menu" data-dropdown-menu>
      <li>
      <% if user_signed_in? %>
      <a href="#"><%= current_user.username %></a>
      <ul class="menu vertical">
        <li><a href="#" data-open="exampleModal1">Edit Profile</a></li>
        <li><%= link_to "Sign Out", destroy_user_session_path, method: 'delete' %></li>
      </ul>
      <% else %>
      <li>
        <a href="#" class="sign-in-button" data-dropdown="drop">Sign In</a>
          <ul id="drop" class="dropdown-menu" data-dropdown-content>
            <%= form_for(resource, as: resource_name, url: session_path(resource_name)) do |f| %>
            <li>
              <div class="small">
                <div id="sign-in">
                 <%= f.label :username %>
                 <%= f.text_field :username, autofocus: true %>
               <%= f.label :password %>
               <%= f.password_field :password, autocomplete: "off" %>
             </div>
             </div>
             <%= f.submit "Sign In", class: "button quiet" %>
            </li>
            <% end %>
          </ul>
        </li>
        <li>
          <a href="#" class="sign-up-button" data-dropdown="drop">Sign Up</a>
          <ul id="drop" data-dropdown-content>
            <%= form_for(resource, as: resource_name, url: registration_path(resource_name)) do |f| %>
            <li>
              <div class="small">
                <div id="sign-up">
                  <%= f.label :username %>
                  <%= f.text_field :username, autofocus: true %>
                  <%= f.label :email %>
                  <%= f.email_field :email, autofocus: true %>
                  <%= f.label :password %>
                  <%= f.password_field :password, autocomplete: "off" %>
                  <%= f.label :password_confirmation %>
                  <%= f.password_field :password_confirmation, autocomplete: "off" %>
                </div>
            </div>
            <%= f.submit "Sign Up", class: "button quiet" %>
            </li>
            <% end %>
          </ul>
        </li>
      <% end %>
    </li>
    </ul>
  </div>
</div>
<div class="flash">
  <% flash.each do |key, value| %>
  <div class="alert alert-<%= key %>"><%= value %></div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title><%= content_for?(:title) ? yield(:title) : "Pollute This Page" %></title>
  <link href='https://fonts.googleapis.com/css?family=Libre+Baskerville' rel='stylesheet' type='text/css'>
  <link href='https://www.mapbox.com/base/latest/base.css' rel='stylesheet' />
  <link href='https://api.mapbox.com/mapbox.js/v2.4.0/mapbox.css' rel='stylesheet' />
  <script src='https://api.mapbox.com/mapbox.js/v2.4.0/mapbox.js'></script>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link rel='shortcut icon' href='path/to/favicon.ico' type='image/x-icon' />
</head>
<%= render 'layouts/top_bar' %>
<body>
  <%= yield %>
</body>
</html>

app/views/pollution_events/_add_event.erb
<div class="row">
  <div class="small-2 small-offset-9 columns text-right add-shop">
    <%= link_to "Add Pollution Event", new_pollution_event_path, { class: "button" } %>
  </div>
</div>

app/views/pollution_events/_edit_event_form.erb
<%= form_for(@pollution_event) do |f| %>
  <div class="row">
    <div class="small-12 medium-6 columns">
      <%= f.label :title, 'Title' %>
      <%= f.text_field :title %>
    </div>
  </div>

  <div class="row">
    <div class="small-12 medium-6 columns">
      <%= f.label :address, 'Address' %>
      <%= f.text_field :address %>
    </div>
  </div>

  <div class="row">
    <div class="small-12 medium-6 columns">
      <%= f.label :description, 'Description' %>
      <%= f.text_area :description %>
    </div>
  </div>

  <div class="row">
    <div class="small-12 medium-6 columns">
      <%= f.label :event_lat, 'Latitude' %>
      <%= f.text_field :event_lat %>
    </div>
  </div>

  <div class="row">
    <div class="small-12 medium-6 columns">
      <%= f.label :event_lng, 'Longitude' %>
      <%= f.text_field :event_lng %>
    </div>
  </div>

  <div class="row">
    <div class="small-12 columns">
      <%= f.submit "Update Event" %>
    </div>
  </div>
<%end%>

app/views/pollution_events/_edit_user_form.erb
<div class="reveal" id="exampleModal1" data-reveal>
  <%= form_for(resource, as: resource_name, url: registration_path(resource_name), html: { method: :put }) do |f| %>
    <%= devise_error_messages! %>
      <%= f.label :email %>
      <%= f.email_field :email, autofocus: true %>
    <% if devise_mapping.confirmable? && resource.pending_reconfirmation? %>
      <div>Currently waiting confirmation for: <%= resource.unconfirmed_email %></div>
    <% end %>
      <%= f.label :password %> <i>(leave blank if you don't want to change it)</i>
      <%= f.password_field :password, autocomplete: "off" %>
      <% if @minimum_password_length %>
        <em><%= @minimum_password_length %> characters minimum</em>
      <% end %>
      <%= f.label :password_confirmation %><br />
      <%= f.password_field :password_confirmation, autocomplete: "off" %>
      <%= f.label :current_password %> <i>(we need your current password to confirm your changes)</i><br />
      <%= f.password_field :current_password, autocomplete: "off" %>
      <%= f.submit "Update", class: "button update fill-lighten0" %>
  <% end %>
  <div class="unhappy">
    Unhappy?
  </div>
  <%= button_to "Cancel my account", registration_path(resource_name), data: { confirm: "Are you sure?" }, method: :delete, class: "button fill-lighten0" %>
  <button class="close-button" data-close aria-label="Close modal" type="button">
    <span aria-hidden="true">&times;</span>
  </button>
</div>

app/views/pollution_events/_event_form.erb
<div class="form-canvas-trigger">
  <% if user_signed_in? %>
  <a href='#step-3' id='canvas-form' class='button add float-right'>
    Add Event
  </a>
  <% end %>
  <div id='step-3' class='row14 col5 pad2 fill-darken3 pin-left offcanvas-left animate'>
    <%= form_for(@pollution_event) do |f| %>
    <a href='#' id="close-button" class='fill-darken0 pad1 icon close'></a>
    <%= f.label :title, 'Title' %>
    <%= f.text_field :title %>
    <%= f.label :address, 'Address' %>
    <%= f.text_field :address %>
    <%= f.label :event_lat, 'Latitude' %>
    <%= f.text_field :event_lat %>
    <%= f.label :event_lng, 'Longitude' %>
    <%= f.text_field :event_lng %>
    <%= f.label :description, 'Description' %>
    <%= f.text_area :description %>
    <%= f.label :url, 'Url' %>
    <%= f.text_area :url %>
    <%= f.submit "Create Event", class: "button secondary form" %>
    <%end%>
  </div>
</div>

app/views/pollution_events/_show_page.erb
<% @pollution_events.each do |event| %>
<div class="show-canvas-trigger">
  <div id="show-<%= event.id %>" class='row13 col6 pad2 fill-darken3 pin-left offcanvas-left animate'>
    <a href='#' class='fill-darken0 pad1 icon close'></a>
    <div class="pad1y pad2x keyline-bottom">
      <h3 class='fancy'><%= event.title %></h3>
      <div class="note contain fill-navy-dark">
      <h6><%= link_to "Link to Article", event.url %></h6>
      <button id="location-fly-<%= event.id %>" class="button quiet">Find</button>
      <br>
      <h8>Latitude: <%= event.event_lat %></h8>
      <br>
      <h8>Longitude: <%= event.event_lng %></h8>
      <br>
      <% if !event.address.nil? %>
      <h8>Address:  <%= event.address %></h8>
      <% end %>
    </div>
        <div class="note contain fill-navy">
          <%= event.description %>
        </div>
    </div>
  </div>
</div>
<% end %>

<script>
  flyToMarker();
</script>

app/views/pollution_events/_sign_up.erb
<%= form_for(@user, registration_path()) do |f| %>
  <div class="row">
    <div class="small-12 medium-6 columns errors">
        <%= devise_error_messages! %>
    </div>
  </div>

  <div class="row">
    <div class="small-12 medium-3 columns">
      <%= f.label :username %>
      <%= f.text_field :username %>
    </div>

  <div class="row">
    <div class="small-12 medium-6 columns">
      <%= f.label :email %>
      <%= f.email_field :email, autofocus: true %>
    </div>
  </div>

  <div class="row">
    <div class="small-12 medium-3 columns">
      <%= f.label :password %> <span class="pass-length">(<%= @minimum_password_length %> characters minimum)</span>
      <%= f.password_field :password, autocomplete: "off" %>
    </div>

    <div class="small-12 medium-3 columns end">
      <%= f.label :password_confirmation %>
      <%= f.password_field :password_confirmation, autocomplete: "off" %>
    </div>
  </div>

  <div class="row">
    <div class="small-12 columns">
      <%= f.submit "Sign Up", class: "button" %>
    </div>
  </div>
<% end %>

app/views/pollution_events/edit.html.erb
<div class="row">
  <div class="small-12 medium-6 columns text-center">
    <h1 class="form-header">Edit Event Information</h1>
  </div>
</div>
<%= render 'pollution_events/edit_event_form' %>
<br>
<div class="row">
  <div class="small-12 medium-3 columns">
    <%= button_to "Delete Event", @pollution_event, action: 'destroy', method: :delete, class: "delete" %>
  </div>
</div>

app/views/pollution_events/index.html.erb
<div class='map-holder'>
  <div class="list-canvas-trigger">
    <a href='#step-4' id='canvas-list' class='button float-right'>
      Recent Events
    </a>
    <div id='step-4' class='list row10 col3 pad2 fill-darken3 pin-left offcanvas-left animate'>
      <a href='#' class='fill-darken0 pad1 icon close'></a>
      <% @pollution_events.each do |event| %>
      <div class="list pad1y pad2x keyline-bottom">
        <a href="#show-<%=event.id%>" id="canvas-show" class=""><%= event.title  %></a>
      </div>
      <% end %>
    </div>
  </div>
  <%= render 'pollution_events/event_form' %>
  <%= render 'pollution_events/show_page' %>
  <%= render 'pollution_events/edit_user_form' %>
  <div class='custom-popup' id='map'></div>
</div>
<script src='https://api.mapbox.com/mapbox.js/plugins/leaflet-markercluster/v0.4.0/leaflet.markercluster.js'></script>
<link href='https://api.mapbox.com/mapbox.js/plugins/leaflet-markercluster/v0.4.0/MarkerCluster.css' rel='stylesheet' />
<link href='https://api.mapbox.com/mapbox.js/plugins/leaflet-markercluster/v0.4.0/MarkerCluster.Default.css' rel='stylesheet' />
<script>
  addMarkerLayer();
</script>

app/views/pollution_events/new.html.erb
<div class="map-holder">

<%= render 'pollution_events/event_form' %>

<div id="new-map" class="small-12 medium-6" ></div>

</div>
<script>
  formMap();
</script>

app/views/pollution_events/show.html.erb
<div class="row columns">
  <div class="row" data-equalizer data-equalize-on="medium">
    <div class="small-12 medium-8 columns" data-equalizer-watch>
      <h1><%= @pollution_event.title %></h1>
    </div>

    <div class="small-12 medium-2 columns text-right edit-event" data-equalizer-watch>
      <div class="edit-delete-button" data-equalizer-watch>
        <% if current_user.id == @pollution_event.user_id %>
          <%= link_to "Edit Event", edit_pollution_event_path(@pollution_event), { class: "button edit-pollutio_event-button" } %>
        <% end %>
      </div>
    </div>
  </div>

  <div class="callout main-info">
    <div class="event-description">
      <span class="bold">Description:</span> <%= @pollution_event.description %>
    </div>

    <div class="row" data-equalizer data-equalize-on="medium">
      <div class="small-12 medium-4 columns">
        <div class="callout secondary" data-equalizer-watch>
          <h4>Address</h4>
          <p>
            <%= @pollution_event.address %>
            <%= @pollution_event.url %>
          </p>
        </div>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="small-12 medium-2 columns">
      <h3>Comments</h3>
    </div>


    <div class="small-12 medium-2 columns text-right">
      <%= link_to "Add Comment", new_pollution_event_comment_path(@pollution_event), { class: "button" } %>
    </div>

  </div>
</div>